[package]
name = "manifest_tool"
description = "helper for manipulating binary files"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true }
num = { workspace = true }
paste = { workspace = true }
rustix = { workspace = true }
tracing = { workspace = true }
zerocopy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
