name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    name: Test (${{ matrix.platform }})
    runs-on: ${{ matrix.runner }}
    environment: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: aarch64-darwin
            runner: [self-hosted, macOS, ARM64]
          - platform: x86_64-linux
            runner: [self-hosted, Linux, X64]
          - platform: aarch64-linux
            runner: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: ./.github/actions/setup-tangram
      - run: bun install --frozen-lockfile
      - name: Verify formatting
        run: |
          bun run auto --format
          git diff --exit-code
      - name: Check
        run: bun run auto --check
      - name: Test
        run: bun run auto --test --retry
